// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7iOMFyfoA5OSjoZ0H7bOeVVFTTDb1cs',
    appId: '1:837196033292:android:dbd2585b4a2669a62f6d29',
    messagingSenderId: '837196033292',
    projectId: 'evans-detailing-app',
    storageBucket: 'evans-detailing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_cShNtX0QI0DQDpD1m2rw5gS3pSrHxuk',
    appId: '1:837196033292:ios:32dfb85a8b80cc6a2f6d29',
    messagingSenderId: '837196033292',
    projectId: 'evans-detailing-app',
    storageBucket: 'evans-detailing-app.firebasestorage.app',
    iosBundleId: 'com.evans.edsApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBg_s7Kcp4xLQpJ54BkJTOSfadyQOs6QE',
    appId: '1:837196033292:web:645e28e469fbccab2f6d29',
    messagingSenderId: '837196033292',
    projectId: 'evans-detailing-app',
    authDomain: 'evans-detailing-app.firebaseapp.com',
    storageBucket: 'evans-detailing-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_cShNtX0QI0DQDpD1m2rw5gS3pSrHxuk',
    appId: '1:837196033292:ios:ca59bdfd99c51a2e2f6d29',
    messagingSenderId: '837196033292',
    projectId: 'evans-detailing-app',
    storageBucket: 'evans-detailing-app.firebasestorage.app',
    iosBundleId: 'com.evans.psalm91',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBg_s7Kcp4xLQpJ54BkJTOSfadyQOs6QE',
    appId: '1:837196033292:web:68a692d491dd894e2f6d29',
    messagingSenderId: '837196033292',
    projectId: 'evans-detailing-app',
    authDomain: 'evans-detailing-app.firebaseapp.com',
    storageBucket: 'evans-detailing-app.firebasestorage.app',
  );

}